[package]
name = "commonmarker"
version = "1.0.0"
edition = "2021"

[dependencies]
magnus = { git = "https://github.com/ianks/magnus", branch = "rb-sys-env" } # waiting for release with full rb-sys backend
comrak = "0.14"

[lib]
name = "commonmarker"
crate-type = ["cdylib"]
