name: Test generic build and installation
concurrency:
  group: "${{github.workflow}}-${{github.ref}}"
  cancel-in-progress: true

on:
  workflow_dispatch:
  pull_request:
    paths:
      - "lib/commonmarker/version.rb"

env:
  CACHE_KEY_PREFIX: "ruby-v1"

# "3.1, 3.2" # SUPPORTED_RUBY_VERSIONS
# ["3.1", "3.2"] # SUPPORTED_RUBY_MATRIX
# "3.2" # LATEST_RUBY_VERSION

jobs:
  generic-package:
    name: "generic-package"
    runs-on: ubuntu-latest
    strategy:
      # fail-fast: false
      matrix:
        platform:
          - x86_64-linux

    steps:
      - uses: actions/checkout@v3

      - uses: oxidize-rb/actions/setup-ruby-and-rust@main
        with:
          ruby-version: "3.2" # LATEST_RUBY_VERSION
          rubygems: latest
          bundler-cache: false
          cargo-cache: true
          cargo-vendor: true
          cache-version: $CACHE_KEY_PREFIX

      - uses: oxidize-rb/actions/cross-gem@v1
        id: cross-gem
        with:
          platform: ${{ matrix.platform }}
          ruby-versions: "3.1, 3.2" # SUPPORTED_RUBY_VERSIONS

      - name: "Test gem build"
        run: ./script/test-gem-build gems ruby

      - uses: actions/upload-artifact@v3
        with:
          name: ${{ env.CACHE_KEY_PREFIX }}-generic-gem
          path: ${{ steps.cross-gem.outputs.gem-path }}
          retention-days: 1

  generic-linux-install:
    needs: ["generic-package"]
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: ["3.1", "3.2"] # SUPPORTED_RUBY_MATRIX
    steps:
      - uses: actions/checkout@v3

      - uses: ruby/setup-ruby-pkgs@v1
        with:
          ruby-version: "${{matrix.ruby}}"

      - uses: actions/download-artifact@v3
        with:
          name: ${{ env.CACHE_KEY_PREFIX }}-generic-gem
          path: gems
      - run: ./script/test-gem-install gems

  # FIXME: does not seem to work
  # generic-darwin-install:
  #   needs: ["generic-package"]
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: ruby/setup-ruby@v1
  #       with:
  #         ruby-version: "3.1"

  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: generic-gem
  #         path: gems
  #     - run: ./script/test-gem-install gems

  # FIXME: does not seem to work
  # generic-windows-install-ucrt:
  #   needs: ["generic-package"]
  #   runs-on: windows-latest
  #   steps:
  #     - uses: actions/checkout@v3

  #     - uses: ruby/setup-ruby-pkgs@v1
  #       with:
  #         ruby-version: "3.1"

  #     - uses: actions/download-artifact@v3
  #       with:
  #         name: generic-gem
  #         path: gems
  #     - run: |
  #         gem update --system 3.3.22 --no-document
  #         gem install --verbose --no-document gems/*.gem
  #         gem list -d commonmarker
  #         bundle exec ruby -e 'require "commonmarker"; puts Commonmarker.to_html("Hello, _world_")'
