name: Tag and Release

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "lib/commonmarker/version.rb"

env:
  CACHE_KEY_PREFIX: "cruby-v1-"

jobs:
  ruby:
    uses: yettoapp/actions/.github/workflows/ruby_gem_release.yml@main
    secrets:
      rubygems_api_key: ${{ secrets.RUBYGEMS_API_BOT_KEY }}
      gh_token: ${{ secrets.GITHUB_TOKEN }}
    with:
      gem_name: commonmarker
      version_filepath: lib/commonmarker/version.rb
      oxidized: true
